#!/bin/sh

# $1: IP maquina 
# $2: comunidad

# Muestra la memoria SWAP total y libre (en Bytes)

# Memoria SWAP total
total=`snmpget -OvQU -v1 -c public localhost memTotalSwap.0`

# Memoria SWAP libre
libre=`snmpget -OvQU -v1 -c public localhost memAvailSwap.0`

# Memoria SWAP Utilizada
utilizada=`expr $total - $libre`

utilizadaB=`expr $utilizada "*" 1024` # en bytes
libreB=`expr $libre "*" 1024`         # en bytes

echo $utilizadaB
echo $libreB
echo mem-swap
echo mem-swap
