#!/bin/sh

# $1: IP maquina
# $2: comunidad

# Muestra el porcentaje de paquetes ICMP  Erroneos

destIn=`snmpget -OvQ -v1 -c $2 $1 icmpInDestUnreachs.0` 

ipOut=`snmpget -OvQ -v1 -c $2 $1 ipOutRequests.0` 

in=`expr $destIn "*" 100`

inTotal=`expr $in "/" $ipOut` 

echo $inTotal
echo $inTotal
echo icmp-dest
echo icmp-dest

