#!/bin/sh

# $1: IP maquina
# $2: comunidad

# Muestra el porcentaje de paquetes ICMP Falta de Recursos

sourcIn=`snmpget -OvQ -v1 -c $2 $1 icmpInSrcQuenchs.0` 

ipOut=`snmpget -OvQ -v1 -c $2 $1 ipOutRequests.0` 

in=`expr $sourcIn "*" 100`

inTotal=`expr $in "/" $ipOut`

echo $inTotal
echo $inTotal
echo icmp-sourc
echo icmp-sourc

