#!/bin/sh

# $1: IP maquina
# $2: comunidad

# Muestra los paquetes ICMP de entrada de error 

# Destino Inalcanzable
items1=`snmpget -OvQ -v1 -c $2 $1 icmpInDestUnreachs.0` 

# Tiempo Excedido
items2=`snmpget -OvQ -v1 -c $2 $1 icmpInTimeExcds.0` 

# Error de Parametros
items3=`snmpget -OvQ -v1 -c $2 $1 icmpInParmProbs.0` 

# Falta de Recursos
items4=`snmpget -OvQ -v1 -c $2 $1 icmpInSrcQuenchs.0` 

total=`expr $items1 + $items2 + $items3 + $items4`

echo $total

