#!/bin/sh

# $1: IP maquina
# $2: comunidad

# Muestra el porcentaje de paquetes IP  con cabecera erronea

ipIn=`snmpget -OvQ -v1 -c $2 $1 ipInReceives.0` 

cabIn=`snmpget -OvQ -v1 -c $2 $1 ipInHdrErrors.0` 

in=`expr $cabIn "*" 100`

inTotal=`expr $in "/" $ipIn`

echo $inTotal
echo $inTotal
echo ip-cab
echo ip-cab

