#!/bin/sh

# $1: IP maquina
# $2: comunidad

# Muestra la carga  mensajes SNMP Enviados y Recibidos

ipIn=`snmpget -OvQ -v1 -c $2 $1 ipInReceives.0` 

ipOut=`snmpget -OvQ -v1 -c $2 $1 ipOutRequests.0` 

snmpIn=`snmpget -OvQ -v1 -c $2 $1 snmpInPkts.0` 

snmpOut=`snmpget -OvQ -v1 -c $2 $1 snmpOutPkts.0` 

in=`expr $snmpIn "*" 100`      
out=`expr $snmpOut "*" 100`   

inTotal=`expr $in "/" $ipIn`
outTotal=`expr $out "/" $ipOut`

echo $inTotal
echo $outTotal
echo snmp-carga
echo snmp-carga

