#!/bin/sh

#
# Instalacion de webHost - MRTG MONITOR en Debian/Ubuntu
#
# Manuel Hervas Ortega - Diseno y Gestion de Redes - UCLM
# 

# $1: Comunidad
# $2: IP Maquina


if [ $# -lt 2 ]
then 
    echo "install <comunidad> <IP>"
    exit 1
fi

## Modificacion de los archivos de configuracion


# Modifica la comunidad y la direccion IP

comunidad=`cat comunidad.webhost`
ip=`cat ip.webhost`

/var/webHost-MRTG/conf/config $ip $2 $comunidad $1

# Borramos temporales

rm -f /var/webHost-MRTG/conf/apache2.cf
rm -f /var/webHost-MRTG/conf/mrtg.cf
rm -f /var/webHost-MRTG/conf/snmpd.cf

# Guardamos la nueva configuracion

echo $1 > comunidad.webhost
echo $2 > ip.webhost



## Instalacion de archivos de configuracion

# Configuracion SNMP
cp /etc/snmp/snmpd.conf /etc/snmp/snmpd.conf-bak # Copia de Seguridad
cp -f /var/webHost-MRTG/conf/snmpd.conf /etc/snmp/snmpd.conf

cp /etc/snmp/snmp.conf /etc/snmp/snmp.conf-bak # Copia de Seguridad
cp -f /var/webHost-MRTG/conf/snmp.conf /etc/snmp/snmp.conf

# Configuracion de APACHE
cp /etc/apache2/httpd.conf /etc/apache2/httpd.conf-bak # Copia de Seguridad
cp -f /var/webHost-MRTG/conf/httpd.conf /etc/apache2/httpd.conf

cp /etc/apache2/sites-available/default /etc/apache2/sites-available/default.bak # Copia de Seguridad
cp -f /var/webHost-MRTG/conf/default /etc/apache2/sites-available/default


# Configuracion de MRTG
cp /etc/mrtg.cfg /etc/mrtg.cfg-bak # Copia de Seguridad
cp -f /var/webHost-MRTG/conf/mrtg.cfg /etc/mrtg.cfg

# Ejecucion

service snmpd restart
service apache2 restart
kill `cat /etc/mrtg.pid`
env LANG=C /usr/bin/mrtg /etc/mrtg.cfg



